version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet build -c Release --no-restore
      - dotnet test -c Release --no-build
      - dotnet pack -c Release --no-build
artifacts:
  base-directory: "src/Amazon.SecretsManager.Extensions.Caching/bin"
  files:
    - "Release/AWSSDK.SecretsManager.Caching.*.nupkg"
