name: Build Test Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true
      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Install .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - name: Install .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.1.x"
      - name: Install .NET Framework (add MSBuild to Path)
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
        # Integration tests need AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2
      - name: Test
        run: dotnet test -c Release --no-build
      - name: Pack
        if: ${{ github.event_name == 'push' }}
        run: dotnet pack -c Release --no-build
      - name: Push to NuGet
        if: ${{ github.event_name == 'push' }}
        # --skip-duplicate ensures changes cannot be pushed to an existing version. Version number has to be incremented in .csproj file
        run: dotnet nuget push "src/Amazon.SecretsManager.Extensions.Caching/bin/Release/AWSSDK.SecretsManager.Caching.*.nupkg" --skip-duplicate --no-symbols --api-key $ {{ secrets.NUGET_TOKEN }} --source "https://api.nuget.org/v3/index.json"
