name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: build (${{ matrix.runner}}, .NET ${{ matrix.dotnet-version }})
    strategy:
      fail-fast: false
      matrix:
        # Run on supported LTS versions
        runner: [ubuntu-latest, windows-latest]
        dotnet-version: [10, 8]
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v6

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install .NET Framework (add MSBuild to Path)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: ${{ runner.arch }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        # Strong name requires disabling xUnit app domains in order to get coverage using coverlet
        # https://github.com/MarcoRossignoli/coverlet/blob/master/Documentation/KnownIssues.md#tests-fail-if-assembly-is-strong-named
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" test/Amazon.SecretsManager.Extensions.Caching.UnitTests ${{ runner.os != 'Windows' && format('--framework net{0}.0', matrix.dotnet-version) || '' }} -- RunConfiguration.DisableAppDomain=true
      - name: Codecov
        uses: codecov/codecov-action@v6
        with:
          directory: test/Amazon.SecretsManager.Extensions.Caching.UnitTests/TestResults
          fail_ci_if_error: true
          use_oidc: true
